%% Build the mex
clear all;
mex hackmat.c -L. -lhackrf -lpthread -R2018a

%% Test reception
FESR=10e6;
fc = 393.24e6;
SDR = HackRF('SampleRate',FESR,...
             'CenterFrequency',fc,...
             'LnaGain',30,...
             'VgaGain',40);

hSP = dsp.SpectrumAnalyzer(...
    'Name',             'Actual Frequency Offset',...
    'Title',            'Actual Frequency Offset', ...
    'SpectrumType',     'Power density',...
    'FrequencySpan',    'Full', ...
    'SampleRate',       FESR, ...
    'YLimits',          [-120,30],...
    'SpectralAverages', 50, ...
    'FrequencySpan',    'Start and stop frequencies', ...
    'StartFrequency',   -FESR/2, ...
    'StopFrequency',    FESR/2,...
    'Position',         figposition([50 30 30 40]));

while(1)
    x=SDR();
    x=x-mean(x);
    hSP(x);
end